#!/bin/bash
###################################################################################
##                                                                               ##
##  This script updates user profile to                                          ##
##    include the key variables $BLJ and $BLJ_PROJ                               ##
##    include the $BLJ/script dir in the $PATH                                   ##
##                                                                               ##
##  By default, the script determines the user's profile.                        ##
##  Optionally, supply the profile to use as an argument.                        ##
##  ex: ./install ~/.bashrc                                                      ##
##                                                                               ##
###################################################################################
BLJ="$( cd "$( dirname ${BASH_SOURCE[0]} )" && pwd )"

# if an arg is given, assume this is the user-profile that user has selected
# otherwise, determine the user_profile
user_profile=$1
if [ ${#user_profile} -eq 0 ]; then
	. $BLJ/script/blj_functions
	user_profile=$(get_default_profile)
	if [ ${#user_profile} -eq 0 ]; then
		echo "Could not determine user profile. Please supply one, example:"
		echo "./install ~/.bash_profile"
		exit 1
	fi
fi

echo "Appending lines to user profile: $user_profile"

# If the profile already exists, back it up.
if [ ! -f "$user_profile" ]; then
	printf '%s\n' '#BioLockJ generated profile' > $user_profile
	echo "    Created profile: $user_profile"
elif [ ! -x "$user_profile" ]; then
	cp $user_profile $user_profile~
	echo "    Saved backup:  $user_profile~"
fi

echo "" >> $user_profile
echo "# installing BioLockJ" >> $user_profile

echo 'export BLJ='"$BLJ" >> $user_profile
echo "    Setting BLJ=$BLJ"

if [ ${#BLJ_PROJ} -gt 0 ] && [ -d ${BLJ_PROJ} ]; then
	echo '    Found existing $BLJ_PROJ: '"$BLJ_PROJ"
	echo "export BLJ_PROJ=$BLJ_PROJ" >> $user_profile
else
	echo '    Setting default BLJ_PROJ=$BLJ/pipelines'
	echo 'export BLJ_PROJ=$BLJ/pipelines' >> $user_profile
fi

echo 'export PATH=$PATH:$BLJ/script' >> $user_profile
# the backticks have to be preserved to appear in the profile
# The result of last-pipeline should be in double quotes in case of file names with spaces.
# The whole string after the = needs to be in double quotes as well.
echo 'alias cd-blj="cd \"`last-pipeline`\"; quick_pipeline_view"' >> $user_profile
# should appear in the profile as:
# alias cd-blj="cd \"`last-pipeline`\"; quick_pipeline_view"

echo ""

VER=$(. $user_profile; biolockj -v) # this line must run BEFORE exporting $BLJ
export BLJ
export BLJ_PROJ=$BLJ/pipelines
CUR=`$BLJ/script/biolockj -v`

if [ ${#CUR} -gt 0 ] && [ ${#VER} -gt 0 ] && [ $CUR == $VER ]; then
	echo "Successfully installed BioLockJ version $VER"
	echo ""
	echo 'Start a new session and run "biolockj --help" to see options.'
else
	echo "Installation process complete."
	echo 'To verify installation, open a new session and type "biolockj --help"'
fi

echo 'Then run a small pipeline:'
echo '"biolockj $BLJ/templates/myFirstPipeline/myFirstPipeline.properties" '
echo ""
