#!/bin/bash
###################################################################################
##                                                                               ##
##  This script updates user profile to                                          ##
##    include the key variables $BLJ and $BLJ_PROJ                               ##
##    include the $BLJ/script dir in the $PATH                                   ##
##                                                                               ##
##  By default, the script determines the user's profile.                        ##
##  Optionally, supply the profile to use as an argument.                        ##
##  ex: ./install ~/.bashrc                                                      ##
##                                                                               ##
###################################################################################
BLJ="$( cd "$( dirname ${BASH_SOURCE[0]} )" && pwd )"

# if an arg is given, assume this is the user-profile that user has selected
# otherwise, determine the user_profile
user_profile=$1
if [ ${#user_profile} -eq 0 ]; then
	. $BLJ/script/blj_functions
	user_profile=$(get_default_profile)
	if [ ${#user_profile} -eq 0 ]; then
		echo "Could not determine user profile. Please supply one, example:"
		echo "./install ~/.bash_profile"
		exit 1
	fi
fi

# If the profile already exists, back it up.
if [ ! -f "$user_profile" ]; then
	printf '%s\n' '#BioLockJ generated profile' > $user_profile
	echo "    Created profile: $user_profile"
elif [ ! -x "$user_profile" ]; then
	cp $user_profile $user_profile~
	echo "    Saved backup:  $user_profile~"
fi

echo 'export BLJ='"$BLJ" >> $user_profile

if [ ${#BLJ_PROJ} -gt 0 ] && [ -d ${BLJ_PROJ} ]; then
	echo "    Found existing "'$BLJ_PROJ: '"$BLJ_PROJ"
	echo "export BLJ_PROJ=$BLJ_PROJ" >> $user_profile
else
	echo 'Setting default BLJ_PROJ=$BLJ/pipelines'
	echo 'export BLJ_PROJ=$BLJ/pipelines' >> $user_profile
fi

echo 'export PATH=$PATH:$BLJ/script' >> $user_profile
echo "alias cd-blj='cd \$(last-pipeline) && echo Moved to most recent pipeline: \`pwd\` && ls'" >> $user_profile

echo "    Saved profile:  $user_profile"
echo "BioLockJ installation complete!"
