#!/bin/bash

## This script navigates the $USER to their most recent pipeline and lists the current directory

. $BLJ/script/blj_functions 

[ ! -d "${BLJ_PROJ}" ] && exit_script "Exit program - BLJ_PROJ: directory not found: ${BLJ_PROJ}" && return
pipeline=$(most_recent_pipeline)
if [ ${#pipeline} -gt 0 ]; then
	echo "Goto latest BioLockJ pipeline: ${pipeline}"
	cd "${pipeline}" && ls "${pipeline}"
else
	echo "No pipelines found in BLJ_PROJ: ${BLJ_PROJ}"
fi
